added report api to the workflow yaml

diff --git a/.github/workflows/retest-api.yml b/.github/workflows/retest-api.yml
--- a/.github/workflows/retest-api.yml
+++ b/.github/workflows/retest-api.yml
@@ -18,3 +18,43 @@ jobs:
         -H 'Content-type: application/json' \
         -H 'auth-token: ${{secrets.TEST_SUITE_TOKEN}}' \
         https://api.testrigor.com/api/v1/apps/NihDdLMoqyeKutE3y/retest
+        
+        sleep 10
+        
+        while true
+        do
+        echo " "
+        echo "==================================="
+        echo " Checking TestRigor retest"
+        echo "==================================="
+        response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/NihDdLMoqyeKutE3y/status' -H 'auth-token: ${{secrets.TEST_SUITE_TOKEN}}' -H 'Accept: application/json')
+          code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+          body=$(echo "$response" | grep status)
+        echo "Status code: " $code
+          echo "Response: " $body
+          case $code in
+            4*|5*)
+              # 400 or 500 errors
+              echo "Error calling API"
+                                               exit 1
+                                               ;;
+                                               200)
+          # 200: successfully finished
+                                               echo "Test finished successfully"
+                                               exit 0
+                                               ;;
+                                               227|228)
+          # 227: New - 228: In progress
+                                               echo "Test is not finished yet"
+                                               ;;
+                                               230)
+          # 230: Failed
+                                               echo "Test finished but failed"
+                                               exit 1
+                                               ;;
+          *)
+                                               echo "Unknown status"
+                                               exit 1
+                                               esac
+          sleep 10
+          done
